### ISSUE TITLE
Worker still shows as "connected" even though no obuilder process is running on the worker

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/ocluster#119]
After restarting the worker's server (pisto) once today without any issues, the subsequent restart ended up with the following failure when restarting the obuilder-worker:
```
Apr 16 15:38:42 pisto ocluster-worker[97755]: 2021-04-16 15:38.42      capnp-rpc [INFO] Connecting to ci3...
Apr 16 15:38:42 pisto ocluster-worker[97755]: 2021-04-16 15:38.42      capnp-rpc [INFO] Doing TLS client-side handshake...
Apr 16 15:38:42 pisto ocluster-worker[97755]: 2021-04-16 15:38.42         worker [INFO] Docker partition: 67% free
Apr 16 15:38:42 pisto ocluster-worker[97755]: 2021-04-16 15:38.42         worker [INFO] Requesting a new job...
Apr 16 15:38:42 pisto ocluster-worker[97755]: 2021-04-16 15:38.42         worker [INFO] Worker loop failed (probably because queue connection failed): (Failure
Apr 16 15:38:42 pisto ocluster-worker[97755]:   "Error calling field(5) -> Failed: Internal error from Registration.register(Queue.pop): Failed: Internal error from Registration.register")
Apr 16 15:38:42 pisto ocluster-worker[97755]: 2021-04-16 15:38.42         worker [INFO] Lost connection to scheduler ((Failure "Failed: Internal error from Registration.register")). Will retry in 9.7s...
```
`ci3` shows pisto as already registered (confirmed using `ocluster-admin`):
```
2021-04-16 14:38.29      capnp-rpc [WARNING] Uncaught exception handling Registration.register: (Failure "Worker already registered!")
```
Stopping the worker service once again for more than 5 minutes did not do anything. Only `ocluster-admin update` actually unlocked the situation:
```
2021-04-16 14:55.54      scheduler [INFO] Worker "pisto.ocamllabs.io" is shutting down
2021-04-16 14:55.54      scheduler [INFO] Restarting "pisto.ocamllabs.io"
2021-04-16 14:55.54      capnp-rpc [WARNING] Uncaught exception handling CapTP connection: (Failure "recv: Unix.Unix_error(Unix.ECONNRESET, \"read\", \"\")") (dropping connection)
2021-04-16 14:55.54      capnp-rpc [WARNING] Error sending messages: Unix.Unix_error(Unix.ECONNRESET, "read", "") (will shutdown connection)
2021-04-16 14:55.54      scheduler [INFO] Release worker "pisto.ocamllabs.io"
```
The cluster should at least send the `Worker already registered` failure in such case.

**Comment by talex5** [comment]
I fixed the error message in #122.

I suspect the problem here is that we're only configuring keep-alives in one direction, so if the worker disappears without resetting the connection (e.g. due to the computer crashing) then the scheduler doesn't notice until it has a reason to send a message. Calling `update` does that.

For the machines in the cluster we collect metrics regularly, which has the same effect, but `pisto` was in an unmonitored test pool.

I made a PR to set keep-alives for capnp in both directions: https://github.com/mirage/capnp-rpc/pull/227
